trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  inputs:
    channel: stable

- task: FlutterBuild@0
  inputs:
    target: 'ios'
    projectDirectory: 
    debugMode: true
    iosCodesign: false

# TODO: Add Android Signing


- task: CopyFiles@2
  inputs:
    contents: '*.app'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
