trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  inputs:
    channel: stable

- task: FlutterBuild@0
  inputs:
    target: 'ios'
    projectDirectory: 
    debugMode: true
    iosCodesign: false

# TODO: Add Android Signing


- task: CopyFiles@2
  inputs:
    contents: '/Users/vsts/agent/2.155.1/work/1/s/build/ios/iphoneos/Runner.app'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1

