trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  inputs:
    channel: stable

- task: FlutterTest@0
  inputs:
    projectDirectory: ''

- task: FlutterBuild@0
  inputs:
    projectDirectory: ''
    target: ios
    iosCodesign: false
# Will need to target all when mac build is worked out

# TODO: Add Android Signing

- task: CopyFiles@2
  inputs:
    contents: '**/*.app'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
