# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  inputs:
    channel: stable

- task: FlutterBuild@0
  inputs:
    projectDirectory: ''
    apkTargetPlatform: android-arm64
    target: apk

- task: FlutterTest@0
  inputs:
    projectDirectory: ''

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build/app/outputs/apk/release/'

