name: dgha_brochure
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.1.2
  font_awesome_flutter: ^8.5.0
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/menu_card/
    - assets/languages/guide_dog_access/
    - assets/languages/guide_dog_info/
    - assets/languages/laws/act/
    - assets/languages/laws/federal/
    - assets/languages/laws/nsw/
    - assets/languages/laws/nt/
    - assets/languages/laws/qld/
    - assets/languages/laws/sa/
    - assets/languages/laws/tas/
    - assets/languages/laws/vic/
    - assets/languages/laws/wa/


  fonts:
    - family: Manjari
      fonts:
        - asset: assets/fonts/Manjari/Manjari-Regular.ttf
        - asset: assets/fonts/Manjari/Manjari-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manjari/Manjari-Thin.ttf
          weight: 100
    - family: RedHatText
      fonts:
        - asset: assets/fonts/Red_Hat_Text/RedHatText-Regular.ttf
        - asset: assets/fonts/Red_Hat_Text/RedHatText-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/Red_Hat_Text/RedHatText-Bold.ttf
          weight: 700
        - asset: assets/fonts/Red_Hat_Text/RedHatText-Medium.ttf
          weight: 500
